= Discussion

VRIFA is a working baseline, not a universal segmenter. The failure modes described below are concrete, mechanism-level, and visible from the operator console, which is the same place the central processing unit (CPU) detection pipeline runs in production.

== Failure Modes

The temporal-locking parameter is the primary diagnostic when results appear noisy on long pauses. The pipeline exposes a temporal-locking window, defaulting to three frames. Locking holds a positive detection in the mask for that many subsequent frames so transient single-frame dropouts do not flicker the boundary. When the operator sets the temporal-locking window higher than the expected pause length in the run, transient detections from earlier in the infusion persist past the moment the front recedes, and the mask grows phantom regions that look like artifacts. The mechanism is not a defect. It is the locking semantics doing exactly what they were configured to do, applied to a sequence whose pauses violate the implicit assumption. The operational consequence is that the temporal-locking window is a per-mold parameter, not a global default, and the failure is visible only on long-pause sequences.

The dynamic-reference calibration window is the second sensitive surface. The pipeline exposes a dynamic-calibration-frames parameter, defaulting to ten, and the dynamic reference mode uses those first ten processed frames to fit a square-root-of-area growth model that subsequently lags the reference frame behind the live frame. The assumption baked into that fit is that early-fill is representative of the growth law. If the first ten processed frames contain race-tracking, an air pocket, or some other anomaly, the fit picks up a poor reference factor and every downstream frame inherits that error. The fix is operator-side, namely choose a calibration window that excludes the anomaly or fall back to one of the static reference modes. The failure is again a misuse of a parameter rather than a numerical defect.

The third failure mode is the only one that is purely a consequence of the artifact pipeline rather than the algorithm. Two encodes of identical raw overlay and heatmap arrays produce MPEG-4 (MP4) streams whose decoded frames differ from the source arrays by a mean per-pixel L2 norm near $5.0$ for the overlay video and near $3.5$ for the heatmap video. The Portable Network Graphics (PNG) outputs, written through a non-codec path, are byte-exact across runs. The mechanism is libavcodec slice-thread nondeterminism in the encode step, not anything in the core algorithm crate. Because the divergence is real and well-characterized, the parity gate runs on PNGs and the structured run summary, and the MP4s are treated as human-review artifacts that are visually identical but not byte-identical.

The fourth failure mode is the inherent ceiling of any tuned classical-CV pipeline. VRIFA does not generalize across substantially different fabric types, lighting setups, or vacuum-bag textures without re-tuning. The default parameters assume a transparent vacuum bag, top-down LED lighting, and a dark mold background, because those are the conditions of the sample videos in the bundled dataset directory. Off-distribution conditions, such as a heavily textured bag, side lighting, or a bright mold surface, can break the default Otsu threshold or push the response distribution outside the range the threshold offset was tuned for. The pipeline provides a percentile-threshold mode, a manual contrast threshold, and an RGB colorspace switch precisely because the default cannot cover every regime, and switching them is the documented response.

== Tradeoffs

VRIFA is built on a deliberate set of tradeoffs that a reader should weigh alongside the benchmark numbers.

We trade an end-to-end accuracy ceiling for explainability and per-mold tunability. A learned segmenter trained on a sufficiently large in-domain corpus would likely exceed the boundary F1 reported in this paper. We do not have a sufficiently large in-domain corpus, and a research group that wants to run a vacuum-assisted resin transfer molding (VARTM) experiment next week does not have the time to label one. The Application contribution is precisely the claim that this tradeoff is favorable in the VARTM regime, where samples are small, ground truth is sparse, and the operator already understands the physics. The pipeline runs on a CPU with no graphics processing unit (GPU), which keeps the deployment surface small and matches how VARTM rigs are actually instrumented in academic and industrial labs.

We trade automated hyperparameter selection for human inspection. There is no Optuna-driven default and no opaque end-to-end model. The operator sees what each parameter does. The roughly fifty configuration parameters are a feature for research, where the practitioner needs to know exactly why a particular result looks the way it does, and a hazard in production, where an unfamiliar operator can choose a temporal-locking window that ruins a run. We are explicit about that tension rather than pretending the parameters are zero-cost.

We trade end-to-end byte-exactness across runs for a working video output. The MP4 streams are not bit-reproducible, and we report rather than hide the encode-tier noise. Bit-reproducibility is preserved where it matters for downstream supervision, namely on the PNG outputs and on the COCO annotations, and abandoned where it does not, namely on the human-review video.

We trade closed-source convenience for an auditable open reference implementation. Anyone can recompile the workspace, rerun the benchmark gate, and check their own outputs against the committed reference outputs directory. The Rust source replaces an opaque baseline with one whose every stage is named, modular, and addressable.

== Scope and Limits

Several setups fall outside the regime VRIFA targets. Opaque vacuum bags break the entire pipeline, because the front is no longer visually observable from above and there is nothing for any image-domain method to detect. Multi-resin systems where dye contrast is intentionally absent fall in the same category, since the response image VRIFA computes is, ultimately, a contrast measurement. Very fast infusions, where the front passes through a region of interest in well under a second, push the temporal-locking and morphology kernels past the regime they were designed for, and the resulting masks lag the true front. Setups where the camera physically moves during infusion break the reference-frame assumption that underpins both static and dynamic reference modes, because the comparison between live and reference frame is no longer between matched pixels.

These are not weaknesses to be patched. They are the boundary of the application domain. A practitioner facing any of them requires a different tool, and stating that boundary explicitly is more useful than overstating the method's operating envelope.

== Implications for the Field

VRIFA is intended to be useful in three concrete ways. Practitioners running a VARTM rig obtain a working flow-front baseline that runs on the laptop next to the rig and produces overlays, masks, heatmaps, and structured annotations without a labeling campaign. Researchers comparing new methods obtain a public reference implementation pinned to a specific commit, a specific configuration, and a specific set of reference outputs, which means a comparison can be replicated rather than approximated. Downstream-detector trainers obtain a labeled bootstrap set produced from the same binary, in COCO, YOLOv5, and Darknet formats, with deterministic PNG masks and deterministic annotations. VRIFA is sufficient to bootstrap detector training and to serve as a reproducible reference implementation for permeability-inversion and process-monitoring studies, and the artifact in the repository is what makes that claim falsifiable. The tradeoffs above are the price of that falsifiability, and they are appropriate for the regime VRIFA targets.
