= Implementation

The Systems contribution rests on a small, audited Rust workspace whose layout, benchmark harness, and stage-parity record are all part of the public artifact. This section walks through that surface so a reader can locate any claim made elsewhere in the paper inside the source tree.

== Workspace Layout

The implementation is organized as a five-crate Cargo workspace. The crate boundaries are functional rather than cosmetic. The core algorithm crate holds the algorithm stages and shared pipeline types and performs no input or output. The input/output crate holds the video reader, the MP4 writers, and the PNG writers. The annotations crate holds the COCO, YOLOv5, and Darknet exporters. The command-line crate holds the binary entrypoint, configuration parsing, and end-to-end orchestration, and is the only crate that depends on every other one. The Python-bindings crate holds the optional PyO3 binding crate that exposes the Rust pipeline to Python so that internal-development tooling can call the same code path that ships in the binary. The shared workspace dependency table pins every shared dependency once, so the algorithm crate, the input/output crate, and the command-line crate cannot drift to incompatible versions of the array container, the computer-vision bindings, or the serialization library.

This split is what makes the rest of the paper auditable. Anything labeled algorithm lives in the core algorithm crate. Anything labeled output side effect lives in the input/output crate or the annotations crate. The benchmark and the parity tooling lean on this separation directly.

== Per-Stage Modularity

Each algorithm stage in the core crate is a single Rust module. There are twelve stage modules. The colorspace conversion stage converts BGR frames into the configured working colorspace. The region-of-interest stage resolves fractional margins and builds the region-of-interest mask. The reference-selection stage implements first, running, previous, absolute, and dynamic reference-frame selection. The peak stage updates the per-pixel peak-brightness map. The delta stage computes the channel-weighted response image. The threshold stage selects scalar thresholds with Otsu, manual, or percentile modes. The morphology stage blurs, thresholds, filters, and produces the cleaned mask. The temporal-lock stage applies persistence-based temporal locking. The overlay stage renders the red-edge overlay over the source frame. The heatmap stage maps the normalized response through the Turbo colormap. The contour-extraction stage extracts bounding boxes and segmentation polygons. The sampling stage selects which frames carry annotations under all-frame, count, and stride modes. A thirteenth file holds conversion helpers between the native array container and the underlying matrix views used by the computer-vision routines, shared across stages and not itself a pipeline stage.

This one-file-per-stage discipline is what makes per-stage parity testing tractable. The diagnostic dumper writes intermediates at named stage boundaries that correspond directly to module names, and the comparison harness checks each named tensor independently. Without the modular layout, the bit-exact result reported below would not be expressible.

== Three-Tier Benchmark

The performance gate lives in the command-line crate as a benchmark target. It runs three workload tiers per sample video. The detector tier runs the per-frame detection pipeline with all output side effects disabled and exists to isolate algorithm cost. The core tier adds MP4 video writing on top of the detector tier and exposes the cost of encoding the overlay, mask, and heatmap streams. The full tier adds PNG export and COCO annotation export on top of the core tier and exposes the cost of writing per-frame artifacts and the JSON annotation file.

The tiering matters because regressions are not all the same kind of regression. If only the full tier slows down, the detector and the encoder are still healthy and the slowdown is in the export path. If the core tier slows down without the detector tier doing the same, the algorithm is unchanged and the encode path is the suspect. Without the split, the test reduces to a single end-to-end timer and a regression in any one layer looks identical.

The harness encodes hard pass/fail thresholds inline as maximum-second budgets. For the first canonical input clip the gates are 32.0, 35.0, and 90.0 seconds for the detector, core, and full tiers. For the second canonical input clip the gates are 5.0, 6.0, and 11.0 seconds. A run that exceeds its tier's gate panics rather than warns, so a regression cannot pass silently.

== Measured Throughput

Three back-to-back invocations of the benchmark target produce stable medians well inside the gates. On the first canonical input clip, the medians are roughly 23.6, 27.2, and 70.3 seconds for the detector, core, and full tiers. On the second canonical input clip, the medians are roughly 3.8, 4.5, and 8.6 seconds. Decomposing those numbers along the tier deltas matches the design intent. On the first clip, the core-minus-detector delta is roughly 3.2 to 5.2 seconds and is attributable to the three MP4 streams written by the input/output crate. The full-minus-core delta on the same video is roughly 43.2 to 47.1 seconds and is attributable to per-frame PNG writes and COCO assembly inside the annotations crate. On the second clip, the same deltas are smaller in absolute terms but track the same shape. The runtime figure (@fig:runtime) plots the per-tier medians alongside the gate thresholds, which lets a reader see at a glance how much headroom the binary holds against its own performance contract.

== Bit-Exact Stage Parity

During development, the only viable way to refactor a numerical pipeline is to test that each refactor preserves the per-stage tensor outputs of a known-good baseline. The harness dumps eight intermediate tensors per frame, namely the converted frame, the raw delta, the blurred delta, the normalized delta, the binary mask, the cleaned mask, the overlay, and the heatmap, and then computes the maximum absolute difference per stage against the reference implementation. On the six diagnostic frames spanning both sample videos, indexed at frames 50, 200, and 500 on the first canonical input clip and at frames 30, 60, and 90 on the second canonical input clip, the per-stage maximum absolute difference is zero across all eight intermediates. There is no CPU-stage divergence on any sampled frame.

Where divergence does appear is in the encoded MP4 streams, and only there. Two encodes of identical raw overlay and heatmap arrays produce decoded MP4 frames with mean per-pixel L2 distances on the order of 5 for the overlay stream and 3.5 for the heatmap stream. Because the upstream tensor dumps are bit-exact, the residual variance is downstream of the pipeline, in the encode-decode intermediate transfer through the video codec, and is consistent with slice-thread nondeterminism in the encoder. The PNG path, which writes directly through the image-encoding library without a video codec, is byte-exact across runs. The parity gate therefore runs on PNGs and on the structured run-summary metadata file, with the MP4s reserved for human review.

== Reproducibility Surface

The repository ships its own evaluation inputs and outputs. Sample videos live in the data directory, including the first and second canonical input clips referenced by the benchmark harness. Reference outputs are committed under a per-input directory tree, each with a run-summary metadata file capturing every configuration parameter that produced it and a COCO-format directory containing the corresponding annotations. The run-summary metadata files double as the artifact-level parity contract, since they pin the colorspace, channel weights, threshold offset, morphology kernels, lock frames, and ROI margin used to generate the committed annotations.

Validation tooling lives outside the Rust workspace, in a development-tooling directory tree. A run-comparison script performs run-level artifact comparison between two output directories. A stage-dump script and its companion comparison script cover the per-stage tensor checks summarized above. A label-frame extractor and a YOLO visualizer support the hand-labeling and detector-bootstrap workflows. The Python tooling is internal-development scaffolding for the Rust binary, not an alternative implementation. Together with the workspace, the benchmark gate, and the committed reference outputs, the validation harness defines the full reproducibility surface for the results reported in this paper.
