= Implementation

The Systems contribution rests on a small, audited Rust workspace whose layout, benchmark harness, and stage-parity record are all part of the public artifact. This section walks through that surface so a reader can locate any claim made elsewhere in the paper inside the source tree.

== Workspace Layout

The workspace at `vrifa-rs/` is a five-crate Cargo workspace declared in `vrifa-rs/Cargo.toml`. The crate boundaries are functional rather than cosmetic. `vrifa-core` holds the algorithm stages and shared pipeline types and performs no input or output. `vrifa-io` holds the OpenCV-backed video reader, the MP4 writers, and the PNG writers. `vrifa-annotations` holds the COCO, YOLOv5, and Darknet exporters. `vrifa-cli` holds the binary entrypoint, configuration parsing, and end-to-end orchestration, and is the only crate that depends on every other one. `vrifa-py` holds the optional PyO3 binding crate that exposes the Rust pipeline to Python so that internal-development tooling under `_dev/` can call the same code path that ships in the binary. The `[workspace.dependencies]` table in `vrifa-rs/Cargo.toml` pins every shared dependency once, so the algorithm crate, the I/O crate, and the CLI cannot drift to incompatible versions of `ndarray`, `opencv`, or `serde`.

This split is what makes the rest of the paper auditable. Anything labeled _algorithm_ lives under `vrifa-rs/crates/vrifa-core/src/`. Anything labeled _output side effect_ lives under `vrifa-rs/crates/vrifa-io/` or `vrifa-rs/crates/vrifa-annotations/`. The benchmark and the parity tooling lean on this separation directly.

== Per-Stage Modularity

Each algorithm stage in `vrifa-core` is a single Rust module under `vrifa-rs/crates/vrifa-core/src/`, exposed from `lib.rs`. There are twelve stage modules. `colorspace.rs` converts BGR frames into the configured working colorspace. `roi.rs` resolves fractional margins and builds the region-of-interest mask. `reference.rs` implements first, running, previous, absolute, and dynamic reference-frame selection. `peak.rs` updates the per-pixel peak-brightness map. `delta.rs` computes the channel-weighted response image. `threshold.rs` selects scalar thresholds with Otsu, manual, or percentile modes. `morphology.rs` blurs, thresholds, filters, and produces the cleaned mask. `lock.rs` applies persistence-based temporal locking. `overlay.rs` renders the red-edge overlay over the source frame. `heatmap.rs` maps the normalized response through the Turbo colormap. `contours.rs` extracts bounding boxes and segmentation polygons. `sampling.rs` selects which frames carry annotations under `all`, `count`, and `stride` modes. A thirteenth file, `cvutil.rs`, holds OpenCV and `ndarray` conversion helpers shared across stages and is not itself a pipeline stage.

This one-file-per-stage discipline is what makes per-stage parity testing tractable. The diagnostic dumper writes intermediates at named stage boundaries that correspond directly to module names, and the comparison harness checks each named tensor independently. Without the modular layout, the bit-exact result reported below would not be expressible.

== Three-Tier Benchmark

The performance gate lives at `vrifa-rs/crates/vrifa-cli/benches/perf_gate.rs` and is registered as a `cargo bench` target. It runs three workload tiers per sample video. The `detector` tier runs the per-frame detection pipeline with all output side effects disabled and exists to isolate algorithm cost. The `core` tier adds MP4 video writing on top of the detector tier and exposes the cost of libavcodec encoding the overlay, mask, and heatmap streams. The `full` tier adds PNG export and COCO annotation export on top of the core tier and exposes the cost of writing per-frame artifacts and the JSON annotation file.

The tiering matters because regressions are not all the same kind of regression. If only `full` slows down, the detector and the encoder are still healthy and the slowdown is in the export path. If `core` slows down without `detector` doing the same, the algorithm is unchanged and the encode path is the suspect. Without the split, the test reduces to a single end-to-end timer and a regression in any one layer looks identical.

The harness encodes hard pass/fail thresholds inline as `max_seconds`. For `input_1` the gates are `32.0`, `35.0`, and `90.0` seconds for the detector, core, and full tiers. For `input_2` the gates are `5.0`, `6.0`, and `11.0` seconds. A run that exceeds its tier's gate panics rather than warns, so a regression cannot pass silently.

== Measured Throughput

Three back-to-back invocations of `cargo bench -p vrifa-cli --bench perf_gate` produce stable medians well inside the gates. On `input_1`, the medians are roughly `23.6`, `27.2`, and `70.3` seconds for the detector, core, and full tiers. On `input_2`, the medians are roughly `3.8`, `4.5`, and `8.6` seconds. Decomposing those numbers along the tier deltas matches the design intent. On `input_1`, the core-minus-detector delta is roughly `3.2` to `5.2` seconds and is attributable to the three MP4 streams written by `vrifa-io`. The full-minus-core delta on the same video is roughly `43.2` to `47.1` seconds and is attributable to per-frame PNG writes and COCO assembly inside `vrifa-annotations`. On `input_2`, the same deltas are smaller in absolute terms but track the same shape. The runtime figure (@fig:runtime) plots the per-tier medians alongside the gate thresholds, which lets a reader see at a glance how much headroom the binary holds against its own performance contract.

== Bit-Exact Stage Parity

During development, the only viable way to refactor a numerical pipeline is to test that each refactor preserves the per-stage tensor outputs of a known-good baseline. The diagnostic record for that work is archived at `vrifa-rs/docs/archive/problem1-stage-diagnosis.md`. The harness dumps eight intermediate tensors per frame, namely `frame_converted`, `delta`, `delta_blur`, `delta_norm`, `binary`, `mask`, `overlay`, and `heatmap`, and then computes the maximum absolute difference per stage against the reference implementation. On the six diagnostic frames spanning both sample videos, indexed `50`, `200`, and `500` on `input_1` and `30`, `60`, and `90` on `input_2`, the per-stage `max_abs_diff` is zero across all eight intermediates. There is no CPU-stage divergence on any sampled frame.

Where divergence does appear is in the encoded MP4 streams, and only there. The same archived note records that two encodes of identical raw `overlay` and `heatmap` arrays produce decoded MP4 frames with mean per-pixel L2 distances on the order of `5` for the overlay stream and `3.5` for the heatmap stream. Because the upstream `.npy` dumps are bit-exact, the residual variance is downstream of the pipeline, in the libavcodec encode-decode round trip, and is consistent with slice-thread nondeterminism in the encoder. The PNG path, which writes directly through the `image` crate without a video codec, is byte-exact across runs. The parity gate therefore runs on PNGs and on the structured run-summary YAML, with the MP4s reserved for human review.

== Reproducibility Surface

The repository ships its own evaluation inputs and outputs. Sample videos live under `data/`, including `data/input_1.mp4` and `data/input_2.mp4` referenced by the benchmark harness. Reference outputs are committed under `reference_outputs/input_1/` and `reference_outputs/input_2/`, each with a `run_summary.yaml` capturing every CLI parameter that produced it and a `formatCOCO/` directory containing the corresponding COCO annotations. The `run_summary.yaml` files double as the artifact-level parity contract, since they pin the colorspace, channel weights, threshold offset, morphology kernels, lock frames, and ROI margin used to generate the committed annotations.

Validation tooling lives outside the Rust workspace, under `_dev/validation/`. `compare_runs.py` performs run-level artifact comparison between two output directories. `dump_stages.py` and `compare_stage_dumps.py` cover the per-stage tensor checks summarized above. `extract_label_frames.py` and `visualize_yolo.py` support the hand-labeling and detector-bootstrap workflows. The Python tooling is internal-development scaffolding for the Rust binary, not an alternative implementation. The full surface, including the workspace, the benchmark gate, the reference outputs, and the validation harness, is released under the MIT license declared in `vrifa-rs/Cargo.toml`.
