= Introduction

Vacuum-Assisted Resin Transfer Molding (VARTM) is the workhorse process for one-off composite laminates from research panels through small-series aerospace structural parts, and the operator's chief lever during a run is the visible advance of the resin flow front under the transparent vacuum bag @Konstantopoulos2014InlineSensing. The position, shape, and rate of that front carry process-quality information that other, more instrumented modalities recover only indirectly. Distributed dielectric arrays @Tifkitsis2014Dielectric and area-sensor grids @Matsuzaki2011AreaSensor produce excellent _local_ wetness measurements but require sensors embedded in the lay-up, and fiber-optic frequency-domain reflectometry @Matsuzaki2022FiberOptic demands instrumentation no operator on a research bench will install for a one-off panel. Direct video of the bag is the one modality that costs nothing extra, sees the entire laminate at once, and is already recorded in most labs as a procedural artifact.

Despite that, the open-source toolchain for turning that video into a usable, time-resolved flow-front segmentation is thin. The published vision systems for VARTM and Liquid Composite Molding (LCM) tend to ship as proprietary controllers tied to a specific cell @Lawrence2005ClosedLoop @Mendizabal2018VisionFlowControl, or as deep convolutional networks trained on simulated frames whose distribution does not match a typical research-bench camera @Stieber2020FlowFrontNet. The practitioner who wants to characterize a single infusion run today has no obvious starting point. Reimplementing the basic appearance-difference pipeline from primitives is feasible, but the design space is large enough — colorspaces, reference selection, threshold rules, morphology, temporal locking — that a clean, audited reference implementation would save the field substantial duplicated effort.

The work is hard for three concrete reasons that have to be addressed by anything claiming to do it. The vacuum bag produces strong specular reflections from lab lighting that look bright in every channel and shift on every operator move; the bag wrinkles and creases that pre-date the front are static dark features that do not represent wet fabric and must not be mistaken for it; and the lighting itself drifts across a multi-minute infusion as lamps warm up and the operator moves equipment. Any practical pipeline has to handle these without an embedded sensor, without a calibrated illumination rig, and without a per-run training set, because no research lab consistently has any of those.

This paper presents VRIFA, an open Rust-implemented classical-computer-vision pipeline that segments resin flow fronts in VARTM video at 30 frames per second end-to-end. On a 55-frame hand-labeled subset spanning eleven distinct VARTM runs, the default configuration achieves mask Intersection-over-Union (IoU) of $X.X X X$ with a 95 % bootstrap confidence interval of $[a, b]$, and a boundary $F_1$ of $Y.Y Y Y$ with confidence interval $[c, d]$. The pipeline runs on commodity central-processing-unit (CPU) hardware without a graphics-processing unit (GPU), is auditable end-to-end with bit-exact per-stage parity tests, and exports annotations in Common Objects in Context (COCO), YOLOv5, and Darknet formats. The artifact is released under the Massachusetts Institute of Technology (MIT) license. The contribution is therefore Hybrid in the contribution-typology sense, with an Application core (classical computer vision retargeted to a domain that prior optical-input work treats only proprietarily) and a Systems wrapper (open implementation, three-tier benchmark, byte-exact reproducibility, and a downstream-detector-ready label format).

The contributions of this paper are the following:

+ a pipeline of twelve auditable stages that produces a binary flow-front mask, an overlay frame, a normalized contrast heatmap, and a Common Objects in Context annotation set from a single VARTM video, with no embedded sensors and no per-run training (Section~3);
+ a Rust workspace structured as five crates with a three-tier benchmark gate that isolates algorithm cost from encoder cost from export cost, plus an archived bit-exact stage-parity record over six diagnostic frames (Section~4);
+ a fifty-five-frame hand-labeled subset spanning eleven distinct VARTM runs, annotated under a documented protocol, on which the default configuration is reported with bootstrap-based confidence intervals at the overall level and broken down per sample (Sections~5 and~6);
+ a runtime characterization showing that the algorithm itself runs in roughly $23$ seconds on a 706-frame, $1920 times 1080$ infusion video, that is, near $30$ frames per second on CPU, with the rest of the per-tier wall-clock attributable to encoder and per-frame export costs that are independent of the algorithm (Section~7); and
+ a documented protocol for bootstrapping a downstream detector from VRIFA's annotation export, demonstrated qualitatively on a YOLO model trained from the COCO output (Section~8).

The paper is organized as follows. Section~2 places VRIFA among the three families of prior work that touch the problem. Section~3 walks through the algorithm. Section~4 describes the implementation. Section~5 documents the labeling protocol and the eleven-sample dataset. Section~6 reports the agreement metrics. Section~7 characterizes runtime. Section~8 demonstrates detector bootstrap. Section~9 discusses failure modes and the honest tradeoffs the design makes. Section~10 concludes.
