
= Related Work

Prior work on Vacuum-Assisted Resin Transfer Molding (VARTM) and the broader Liquid Composite Molding (LCM) family touches the flow front from three different directions. A first body of work uses flow-front information to act on the process through closed-loop control or fault response. A second body observes the process to characterize it, typically with embedded sensors or auxiliary cameras for offline study. A third body models the underlying Darcy physics or inverts it from sparse measurements. The work in this paper sits at the seam of all three because the integrated pipeline produces the per-frame full-field flow-front mask that the first family assumes is available, that the second family currently approximates with sensor grids, and that the third family typically receives only as a handful of digitized contours from a manual annotation pass. The remainder of this section addresses each family in turn and closes with the specific gap that the integrated pipeline fills.

== Use: vision and sensors that act on the VARTM process

Closed-loop VARTM controllers have a long lineage. Multi-segment injection-line work coupled point sensors with a finite-element flow model so that valves could be re-sequenced in real time to chase the flow front toward starved regions and away from race-tracks @Lawrence2005ClosedLoop. The control loop is genuinely real time and the empirical results are convincing for plate geometries, but the feedback signal is a sparse vector of resin-arrival times at instrumented locations, which means dry-spot detection only works when a sensor happens to lie inside the dry region. The integrated pipeline differs by treating every pixel inside the bag as a potential sensor, so dry-spot evidence is not gated on instrumentation density.

A more recent line of work replaces point sensors with a top-mounted camera. Lekanidis and Vosniakos built a webcam-plus-microcontroller rig for VARI that segments the resin flow front with a classical Matlab pipeline (Gaussian blur, grayscale conversion, contrast stretch, Otsu binarization, closing on a 10-pixel disk, Sobel edge detection, opening with a 120-pixel area threshold, dilation) and toggles inlet valves on the resulting front position @LekanidisVosniakos2020IJMMS. Almazán-Lázaro and co-workers close a similar loop on resin infusion, regulating flow-front velocity to an experimentally-determined optimum with a PID over a pipeline that combines region-of-interest cropping, Scaramuzza-style lens-distortion correction, histogram equalization, first-frame absolute differencing, grayscale conversion, a 5-by-5 mean filter, Sobel-gradient segmentation, paired erosion and dilation, and small-area removal @AlmazanLazaro2018Materials @AlmazanLazaro2022JMP. Both systems demonstrate that vision alone can drive VARTM control, but neither reports the joint or individual contribution of the segmentation primitives they use, neither evaluates the segmentation against a labeled video benchmark, and both treat the segmentation step as a black box that succeeds or fails as a unit. The work in this paper differs by combining the same family of primitives in one configuration and reporting the agreement of the joint configuration and the IoU cost of disabling each component on a labeled subset spanning eleven distinct infusion runs.

Adjacent to control are vision-based defect-detection systems for composites more broadly @Ren2024MaterialDefectSurvey. These pipelines now lean almost entirely on convolutional or transformer detectors trained on hand-curated defect crops, and a recurring bottleneck across that survey is the cost of pixel-accurate labels. The work in this paper is upstream of that bottleneck. The integrated classical pipeline produces per-pixel front masks deterministically and characterizes which components are responsible for which IoU points, which gives a downstream learned detector @Jocher2023YOLOv8 @Ronneberger2015UNet a labeled-data starting point whose error structure is decomposable rather than monolithic.

== Observe: sensor-based and vision-based process characterization

A second family treats the flow front as something to be measured rather than acted on. Konstantopoulos and co-authors review the in-line sensing landscape and group the field around dielectric, thermal, ultrasonic, fiber-optic, and electrical-resistance sensors @Konstantopoulos2014InlineSensing. Dielectric tracking by Yenilmez and Sozer and others gives unsaturated and saturated front positions at each electrode pair, with an installation cost that is hard to beat, but the spatial resolution of the resulting front is limited by the electrode pitch @Tifkitsis2014Dielectric. Matsuzaki and co-workers dramatically improve coverage with an area-sensor array that tiles a polyimide film into a dense capacitive matrix and recovers the impregnated-area ratio per cell, which is the closest sensor-side analogue to a full-field flow-front mask @Matsuzaki2011AreaSensor. The resulting front is, however, still a quantized grid that is destructive to instrument inside production tooling and that adds permeability to the stack-up.

Fiber-optic strategies use Fiber Bragg Grating arrays or Optical Frequency Domain Reflectometry to time-stamp resin arrival at every grating along an embedded fiber, and recent distributed-sensing implementations push toward life-cycle structural health monitoring of large CFRP parts @Matsuzaki2022FiberOptic. These methods deliver excellent temporal precision and can survive infusion and cure, but the same coupling between sensor density and front fidelity reappears, since arbitrary front shapes between gratings are interpolated, not measured. A small but growing thread fuses dielectric and visual data with learning-based fusion. The recent AI-based dielectric-plus-visual monitor by Esposito and co-workers detects and tracks the front with a YOLO detector trained on labeled video and uses dielectric channels as a redundant signal @Esposito2025AIFusion. That pipeline is closest in spirit to the front producer described here, but it is reported on a single-fabric study, it does not report which preprocessing components carry which IoU points, and the detector is trained rather than classical. The work in this paper differs by combining the classical primitives the prior systems use in isolation, evaluating the joint configuration on a labeled subset spanning eleven infusion runs, and reporting the marginal IoU effect of each component.

Stieber and co-workers show that learning a flow-front "image" from a sparse pressure-sensor grid is a tractable surrogate task and report time-step accuracy near 92 percent on simulated injection runs @Stieber2020FlowFrontNet. A follow-on extends the same approach to material-property inference under a simulation-to-real transfer pretext and shows IoU around 0.50 with transformer backbones @Stieber2023SimToReal. These are excellent demonstrations of what a network can learn given ground-truth flow-front maps. They presume the maps exist, and they obtain them from FEM injection simulations rather than from real video. The work in this paper addresses the upstream half of that pipeline by producing per-pixel front masks from real VARTM video that such networks would need for fine-tuning, and by reporting which components of the upstream segmenter contribute which IoU points.

== Model: physics-based forward and inverse flow-front formulations

The third family models the front analytically or numerically. Forward Darcy-flow simulators for VARTM now routinely couple a depth-averaged Darcy solver to a level-set front with high-permeability-medium layers and progressive-saturation effects @Adhikari2021HPMLevelSet, and end-to-end VARTM simulation with reinforcement compaction and post-filling pressure relaxation has been validated experimentally for plate and stiffened-plate geometries @Govignon2008FullField. These models predict the flow front given a permeability field and a boundary condition. The inverse direction is harder. Comas-Cardona and co-authors recover an in-plane permeability field by coupling optical areal-weight measurement with central-injection front observation, and similar work by Di Fratta, Klunker, and Ermanni inverts pressure-sensor traces against an analytic front model to update injection parameters online @ComasCardona2014OpticalInverse @DiFratta2016PressureInversion. These methods are mathematically careful, but they all depend on having the front geometry as input. In Comas-Cardona that geometry comes from a manually thresholded plate experiment, and in the sensor-based works it comes from arrival-time interpolation. The integrated pipeline lowers the cost of populating that input by producing per-frame, per-pixel front masks directly from the production video stream that is already being recorded for documentation.

Recent work has begun to merge model and learning. Park and co-authors couple electromechanical PZT signals to a tree-plus-GAN model that both identifies the live front and forecasts its near-future position @Park2025FlowFrontGAN, and physics-informed neural permeability inversion has been explored in synthetic Darcy benchmarks @Mao2026PINNInversion. Both are promising for closed-loop VARTM, and both inherit the same dependency on a labeled flow-front signal during training. Without an open, retargetable source of that signal in real video, every group reproducing or extending these methods has to instrument a new bench.

== Adjacent: post-cure NDE and digital-twin closed-loop systems

Defect characterization in cured composite parts has a substantial post-cure non-destructive-evaluation literature. Ultrasonic C-scan recovers delamination, voids, and porosity at sub-millimeter resolution @WronkowiczKatunin2022UltrasonicNDE, infrared thermography covers larger areas at lower spatial resolution and is non-contact, and fusion of C-scan with thermographic phase imaging measurably improves shallow-defect signal-to-noise on Carbon-Fiber-Reinforced-Polymer (CFRP) laminates @Cao2024UltrasoundThermographyFusion. These methods sit downstream of the work in this paper. The defect they detect is the consequence of a particular flow trajectory, and the per-frame front masks produced here describe that trajectory directly while it is still acting.

A complementary thread fuses in-situ sensor data, forward simulation, and learned controllers into closed-loop digital-twin systems. AI-driven digital twins for polymer composite manufacturing identify defect signatures in real time and use model-predictive control over vacuum and thermal cycles to suppress dry-spot formation @ManiscalcoBrancaccio2026DigitalTwin, and distributed carbon-nanotube-textile sensors provide the dense in-plane wetness signal these systems consume during infusion @Boschetto2020CNTTextile. The integrated front-segmentation pipeline produces a per-pixel signal of the same physical observable, namely wet versus dry everywhere inside the bag, at lower instrumentation cost, and is therefore a direct upstream candidate for the sensing layer of such systems.

== Building blocks: classical CV foundations

The integrated pipeline stays deliberately within well-understood classical operators. Otsu's bimodal threshold provides the wet-versus-dry separation in each frame @Otsu1979Threshold, the Suzuki-Abe topological-border-following algorithm provides hierarchically consistent contour extraction over the resulting binary @Suzuki1985Border, and the Kim et al. codebook background model handles the slow illumination drift typical of multi-hour infusions without retraining @Kim2005Codebook. None of these primitives is novel. The contribution of this paper is the joint composition, the per-stage parameterization, and the per-component evidence that the joint matters on a labeled multi-mold subset. The recent material-defect-detection survey notes that the absence of characterized preprocessing pipelines is a primary bottleneck for deploying deep models in composite quality control @Ren2024MaterialDefectSurvey, and modern detectors such as YOLO illustrate why that bottleneck matters because they are starved for in-domain pixel labels rather than for capacity @Redmon2016YOLO.

== Where this work fits

The three families above all touch the flow front, but none of them reports the question this paper answers. The control family treats segmentation as a black box and reports downstream control quality, not segmentation quality. The observation family reports excellent agreement at sensor electrodes and gratings, but interpolates between them rather than measuring per-pixel front geometry from video. The modeling family assumes a per-pixel front exists and consumes it, which is precisely the artifact the upstream segmenter must produce. Within the camera-based subset of the observation family, prior systems differ in which subset of the available primitives they use and report only end-to-end behavior on a single mold. None reports the joint contribution of the components in use, none reports the marginal cost of any component left out, and none evaluates against a labeled video benchmark spanning more than one mold. This paper supplies that evidence on eleven distinct infusion runs and on a 55-frame hand-labeled subset.

#figure(
  // image("/typst/figures/competitor_pipelines.pdf", width: 100%),
  rect(width: 100%, height: 2.4in, stroke: 0.5pt, inset: 8pt)[
    _Competitor-pipeline comparison placeholder._ Three-row diagram
    showing the per-frame stage sequence of the two prior camera-CV
    pipelines that report enough method detail to reproduce, and
    the integrated pipeline of this work. Top row: Lekanidis and
    Vosniakos 2020 (IJMMS) -- decode, ROI crop, Gaussian blur,
    grayscale, contrast stretch, Otsu binarize, foreground swap,
    closing on disk-13 SE, Sobel edge, opening with area threshold
    120, dilation. Middle row: Almazán-Lázaro 2022 (J Manuf
    Processes) -- decode, ROI crop, Scaramuzza distortion correction,
    histogram equalization, first-frame absolute difference,
    grayscale, 5-by-5 mean filter, Sobel gradient, erosion, dilation,
    small-area removal. Bottom row: this work (16 stages from
    fig:pipeline). Each row is a horizontal chain of named
    operations drawn in the same brand palette as fig:pipeline; boxes
    that appear only in the integrated pipeline (peak-brightness
    reference, darken-only clip, dynamic-lag reference, post-delta
    blur as a discrete stage, paired close+open with min-area
    filter, temporal lock, run-time camera-shift registration) are
    bordered in garnet so the reader sees what the integrated
    pipeline adds at a glance. Boxes in the prior pipelines that
    have no analogue in this work (Almazán's Scaramuzza
    lens-distortion calibration) are bordered in atlantic.
  ],
  caption: [
    Per-frame stage comparison of the three classical-CV pipelines
    for VARTM/LCM that report enough method detail to reproduce.
    Boxes bordered in garnet are present only in the integrated
    pipeline.
  ],
) <fig:competitor_pipelines>

The lens-distortion-calibration step that Almazán-Lázaro and co-workers apply once at setup time @Scaramuzza2006Toolbox is the only operation in either prior pipeline that has no analogue in this work, and the run-time camera-shift registration described in Section~3 is the only operation in this work that has no analogue in either prior pipeline. The two are complementary axes; a deployed system would benefit from both.
