#import "../lib.typ": td

= Related Work

This work builds upon four research pillars of the composite-manufacturing and computer-vision literatures. The first pillar is the forward and inverse physical modeling of resin flow in Liquid Composite Molding (LCM) and Vacuum-Assisted Resin Transfer Molding (VARTM), which predicts the per-pixel front from a permeability field or recovers a permeability field from observed front geometry. The second pillar is the embedded-sensor observation of the front during infusion, which produces dense in-plane wetness signals at an instrumentation cost that scales with sensor density. The third pillar is the real-time control of resin infusion, where the front signal drives valves, vents, or pumps, and where a recent camera-based subset replaces point sensors with computer vision. The fourth pillar is the classical computer-vision tradition of thresholding, morphology, image alignment, and topological border-following, whose named operators the integrated pipeline composes into a per-frame per-pixel mask producer. The remainder of this section addresses each pillar in turn. The third pillar's camera-based subset is the closest prior art and receives its own subsection while the final subsection attributes the operators of the fourth pillar to their canonical sources and names the specific evidence gap this paper supplies.

== Modeling, sensing, and control of the flow front

The VARTM flow-modeling literature traditionally treats the flow front as a given input. Forward simulators predict where resin will flow across the laminate given material permeability and inlet conditions, and have been validated against experiments on flat and stiffened plates @Adhikari2021HPMLevelSet @Govignon2008FullField. These geometries are simpler than the multi-section preforms used in production parts, which limits how directly the simulator results transfer to operational benches. Conversely, inverse methods work backward from the observed front. One approach combines overhead camera measurements of how fabric thickness varies across the laminate with a center-injection experiment to recover a 2D permeability map @ComasCardona2014OpticalInverse. Another method compares live pressure-sensor data against a closed-form Darcy-flow model of the moving front to adjust injection parameters on the fly @DiFratta2016PressureInversion. Learning-based variants extend the same thread, using piezoelectric sensors and a hybrid learned model to identify and forecast the front @Park2025FlowFrontGAN, or physics-informed neural networks to recover permeability fields from simulated Darcy data @Mao2026PINNInversion. A related line of work trains surrogate models to predict the 2D front map from sparse pressure sensors on simulated runs @Stieber2020FlowFrontNet, later extending the same approach to material-property inference under simulation-to-real transfer @Stieber2023SimToReal. Every method discussed above depends on a front map, which is currently obtained from finite-element simulation or manual annotation of plate experiments. However, simulation and hand-labeling are slow and bench-specific, which prevents real-time front estimation during an active infusion. The integrated pipeline we introduce produces that map directly from production video, removing both bottlenecks.

The observation literature measures the front directly but does so through instrumentation that discretizes it, traditionally through modalities like dielectric, thermal, ultrasonic, fiber-optic, and electrical-resistance @Konstantopoulos2014InlineSensing. Dielectric tracking gives unsaturated and saturated front positions at each electrode pair at an installation cost that is hard to beat, but the spatial resolution of the resulting front is bounded by the electrode pitch @Tifkitsis2014Dielectric. Area-sensor arrays dramatically improve coverage by tiling a polyimide film into a dense capacitive matrix and recovering the impregnated-area ratio per cell, which is the closest sensor-side analogue to a full-field flow-front mask @Matsuzaki2011AreaSensor. However, the resulting front is still a quantized grid limited by the cell size, and the polyimide film must also be embedded in the lay-up, which is intrusive to install in production tooling and alters the local permeability of the part being measured. Fiber-optic strategies use Fiber Bragg Grating arrays or Optical Frequency Domain Reflectometry to time-stamp resin arrival at every grating along an embedded fiber, with recent distributed-sensing implementations pushing toward life-cycle structural-health monitoring of large Carbon-Fiber-Reinforced-Polymer (CFRP) parts @Matsuzaki2022FiberOptic. These methods deliver excellent temporal precision and can survive infusion and cure, but the same tradeoff between sensor density and front accuracy reappears, since arbitrary front shapes between gratings are interpolated rather than measured. Distributed carbon-nanotube textile sensors push the spatial-coverage axis further by integrating the sensing layer into the lay-up itself @DaiThostenson2020CNTTextile, but the textile becomes a permanent part of the cured laminate and adds its own material to the stack-up. Across all of the aforementioned methods, the resolution of the resulting front is limited by the spacing of the sensing elements, and the approaches that come closest to dense coverage do so by embedding the sensor into the part being measured. The integrated pipeline we introduce avoids both costs by reading the front with a single overhead camera.


The control literature is often the largest downstream user of the flow front data, since it uses the front signal to act on the process in real time. Early closed-loop systems couple point-sensor arrival times to a finite-element flow model so that multi-segment injection valves can be re-sequenced to chase the front toward starved regions and away from race-tracks @Lawrence2005ClosedLoop. The broader closed-loop and sensor-driven control thread for resin transfer molding has been developed for decades @SozerBickertonAdvani2000OnLine @NielsenPitchumani2002ClosedLoop @HsiaoAdvani2004FlowSensingI @Devillard2005FlowSensingII @LawrenceFriedAdvani2005AuxiliaryGates @MinaieChen2005Adaptive. A more recent camera-based subset replaces point sensors with a top-mounted camera, segments the front from the live video stream with a classical pipeline of difference-and-morphology operators, and toggles inlet valves on the resulting front position @LekanidisVosniakos2020IJMMS @AlmazanLazaro2018Materials @AlmazanLazaro2022JMP. The camera-based subset is the most promising of these for closed-loop control, because a single overhead camera gives the controller a per-pixel front signal at every frame without the electrode-pitch limit of dielectric arrays or the embedded-sensor cost of area or fiber-optic arrays. Recent fusion work supports this trend, using a learned You-Only-Look-Once (YOLO) detector on camera video as the primary segmenter and adding dielectric channels only as redundancy @Esposito2025AIFusion.


Adjacent to these three pillars is a post-cure non-destructive-evaluation literature and a closed-loop digital-twin literature, both of which the integrated pipeline does not build on directly but which sit naturally downstream of it. Defect characterization in cured composite parts reads the trace of the front after the fact. Ultrasonic C-scan recovers delamination, voids, and porosity at sub-millimeter resolution @WronkowiczKatunin2022UltrasonicNDE, infrared thermography covers larger areas at lower spatial resolution and without contact, and fusion of C-scan with thermographic phase imaging measurably improves shallow-defect signal-to-noise on CFRP laminates @Cao2024UltrasoundThermographyFusion. The defects these methods detect are the consequence of a particular flow trajectory, and the per-frame mask produced by the integrated pipeline describes that trajectory directly while it is still acting. A complementary digital-twin thread fuses in-situ sensor data, forward simulation, and learned controllers to identify defect signatures in real time and to use model-predictive control over vacuum and thermal cycles to suppress dry-spot formation @Jha2026DigitalTwin. Such systems are candidate consumers of the per-pixel front signal at the sensing layer, since the wet-versus-dry observable they require is exactly what the pipeline emits.

== Camera-based front segmentation

The closest prior art to the integrated pipeline is the camera-CV subset of the control family above, and the contribution of this paper is best located against it. Lekanidis and Vosniakos built a webcam-plus-microcontroller rig for Vacuum-Assisted Resin Infusion (VARI) that segments the resin flow front with a Matlab pipeline of Gaussian blur, grayscale conversion, contrast stretch, Otsu binarization, closing on a ten-pixel disk, Sobel edge detection, opening with a one-hundred-twenty-pixel area threshold, and dilation, and toggles inlet valves on the resulting front position @LekanidisVosniakos2020IJMMS. Almazán-Lázaro closes a similar loop on resin infusion, regulating flow-front velocity to an experimentally-determined optimum with a Proportional-Integral-Derivative (PID) controller over a pipeline that combines region-of-interest cropping, Scaramuzza-style lens-distortion correction, histogram equalization, first-frame absolute differencing, grayscale conversion, a five-by-five mean filter, Sobel-gradient segmentation, paired erosion and dilation, and small-area removal @AlmazanLazaro2018Materials @AlmazanLazaro2022JMP. Esposito and colleagues replace the classical segmenter with a learned YOLO detector trained on labeled video, fuse the output with dielectric channels for redundancy, and demonstrate real-time front monitoring and prediction on a single-fabric study @Esposito2025AIFusion. The three systems demonstrate that vision alone, or vision plus dielectric, can drive VARTM monitoring and control on the bench at which they were instrumented.

What the three systems do not report is the question this paper answers. They report end-to-end behavior, never the joint or individual contribution of the segmentation primitives in use. They treat the per-frame mask producer as a unit that succeeds or fails as a whole rather than as a composition of named operators whose marginal contributions can be measured. They disagree on details that propagate directly into how robust each pipeline is to disturbance. The Almazán-Lázaro pipeline clips the difference so that only darkening counts as wetting and the Lekanidis-Vosniakos pipeline does not. The Lekanidis-Vosniakos pipeline tracks a per-pixel running maximum as the reference and the Almazán-Lázaro pipeline pins a single early frame as a first-frame absolute differencing reference. The Esposito pipeline imposes a learned temporal regularization through the YOLO detector trained on sequential frames, and the two classical pipelines operate frame-by-frame on the segmentation side. None of these disagreements has been adjudicated on a labeled multi-mold benchmark because no such benchmark exists in the published literature. Each prior paper reports excellent agreement on the single mold it was developed for, and the reader is left to guess which knob settings would carry over to a different bench.

Adjacent to the front-segmentation literature is a broader composite-defect-detection literature that increasingly leans on deep convolutional and transformer detectors trained on hand-curated defect crops. A recent material-defect-detection survey identifies pixel-accurate labels as the primary bottleneck, ahead of model capacity @Ren2024MaterialDefectSurvey. Modern detectors such as YOLO @Redmon2016YOLO @Jocher2023YOLOv8 and segmentation architectures such as U-Net @Ronneberger2015UNet illustrate why this matters, because they are starved for in-domain pixel labels rather than for parameters. A per-pixel front-mask producer that runs deterministically on production video, as opposed to a learned detector that requires its own labeled-video training set per bench, is therefore upstream of that bottleneck. The integrated pipeline of this paper is positioned to fill that upstream role, and the 55-frame hand-labeled benchmark introduced alongside it is positioned to support evaluation of any future learned segmenter that wants to claim improvement over the classical baseline.

Two specific operators define the difference between the prior camera-CV pipelines and the integrated pipeline. The lens-distortion calibration step applied once at setup time in Almazán-Lázaro @Scaramuzza2006Toolbox is the only operation in either prior camera-CV pipeline that has no analogue in this work, and the run-time camera-shift registration described in Section~3 is the only operation in this work that has no analogue in either prior camera-CV pipeline. The two are complementary axes rather than substitutes, and a deployed system would benefit from both.

== Classical computer-vision primitives

The integrated pipeline stays deliberately within well-understood classical operators because the empirical claim of this paper is per-component, and a learned segmenter would conflate the contributions of the components inside it. Every named stage maps to a primitive with a canonical attribution and a documented behavior, and the per-component ablation reported in Section~5 is well defined precisely because each stage can be disabled independently. Wet-versus-dry separation in each frame is performed by Otsu's between-class-variance threshold @Otsu1979Threshold, with the Triangle method @Zack1977Triangle exposed as an alternative when one class dominates the histogram. Camera-shift registration combines phase correlation @KuglinHines1975PhaseCorrelation on a Hanning-windowed downsample with iterative Enhanced Correlation Coefficient (ECC) refinement @EvangelidisPsarakis2008ECC, run on a static-edge mask of the current region of interest so the warp is driven by mold and frame edges that do not move with the wet front. Polygon export to Common Objects in Context (COCO) and YOLO formats uses the Suzuki-Abe topological-border-following algorithm @Suzuki1985Border, optionally simplified by Douglas-Peucker reduction at a user-supplied tolerance @DouglasPeucker1973. The peak-brightness reference, the darken-only clip, the post-delta blur, the paired close-and-open morphology with an area-floor connected-components filter, and the count-based temporal lock are per-pixel compositions of arithmetic and comparison whose value lies in the joint configuration in which they appear rather than in any single canonical attribution.

None of these primitives is novel in isolation. The contribution of this paper is the joint composition, the per-stage parameterization, and the per-component evidence that the joint matters on a labeled multi-mold subset. The four pillars on which this work builds each touch the flow front from a distinct angle, and none on its own supplies the evidence this paper provides. The modeling pillar consumes a front map it does not measure, and obtains the map from simulation. The observation pillar measures a front it cannot densely cover, and bounds front fidelity by sensor pitch. The control pillar acts on a front it produces with a segmenter it does not characterize per component. The classical computer-vision pillar supplies the named primitives but does not on its own evaluate any composition of them on a multi-mold VARTM benchmark. The camera-CV subsystems closest to this work, Lekanidis-Vosniakos and Almazán-Lázaro, differ in which subset of the classical primitives they use and report only end-to-end control behavior on a single mold. None reports the joint contribution of the components in use, none reports the marginal cost of any component left out, and none evaluates against a labeled video benchmark that spans more than one mold. This paper supplies that evidence on a 55-frame hand-labeled subset spanning eleven distinct infusion runs, with the component-removal ablation reported both as an eleven-sample mean and as a per-sample breakdown.
