[package]
name = "vrifa-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "vrifa"
path = "src/main.rs"

[[bench]]
name = "perf_gate"
harness = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
image.workspace = true
indexmap.workspace = true
ndarray.workspace = true
ndarray-npy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
vrifa-annotations = { path = "../vrifa-annotations" }
vrifa-core = { path = "../vrifa-core" }
vrifa-io = { path = "../vrifa-io" }
