[package]
name = "vrifa-py"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "vrifa_py"
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
ndarray.workspace = true
numpy.workspace = true
pyo3.workspace = true
vrifa-cli = { path = "../vrifa-cli" }
vrifa-core = { path = "../vrifa-core" }

[package.metadata.maturin]
python-source = "../../python"
module-name = "vrifa.vrifa_py"
